### ISSUE TITLE
Add support for auto-merge

### ISSUE THREAD

**Issue by Sese-Schneider** [repository-settings/app#402]
## Prerequisites:
![image](https://user-images.githubusercontent.com/14337484/105974322-12aecc00-608e-11eb-9ea7-65702053aab4.png)

* [GitHub Docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request)
* I couldn't find API availability - however I'm not that familiar with GitHub API docs so it might be.

## New Feature

Request: A config field allowing the repository settings "Allow auto-merge" to be controlled.

**Comment by travi** [comment]
I am very interested in this functionality as well, but have also not found any mention of it in the API docs yet. Since this is new functionality and there always seems to be some lag before things like this show up in the API, it's not surprising. 

The best thing that folks wanting this functionality can do for now is to [contact support](https://github.com/contact) and ask for the functionality to be exposed through the API. Please report as responses that you get here, so we can get some idea of any progress. Also, feel free to reference this issue to help them gauge interest from the community.

**Comment by ocean90** [comment]
The API has been updated to support `allow_rebase_merge`, see https://github.blog/changelog/2021-08-17-maintainers-can-now-manage-the-availability-of-auto-merge-in-a-repository/. It seems like we just have to add `allow_rebase_merge: true` to the config and no other changes are required?

**Comment by travi** [comment]
great news! thanks for the heads up @ocean90!

**Comment by Sese-Schneider** [comment]
Feature is supported now.
